// Growth Asset Pack generation engine.
//
// Produces the five client-facing deliverables that make up the premium Client
// Acquisition Infrastructure Pack. Each deliverable is generated by its own
// focused model call (so the output stays deep instead of shallow, and so a
// single deliverable can be regenerated on its own). All calls share the same
// grounding context: the real business profile plus the heuristic audit
// intelligence briefing.

import { openai, ASSET_MODEL } from "./openai";
import type { AuditIntelligence } from "./audit-intelligence";
import { intelligenceToPromptBlock } from "./audit-intelligence";
import type {
  AssetPack,
  AssetSection,
  GrowthAuditFile,
  LeadQualificationFile,
  EmailNurtureFile,
  SmsFollowUpFile,
  BookingSystemFile,
} from "@/types";

export interface BusinessProfile {
  name: string;
  industry: string | null;
  category: string | null;
  city: string | null;
  rating: number | null;
  reviewCount: number | null;
  website: string | null;
  description: string | null;
}

export interface GenerationContext {
  business: BusinessProfile;
  intel: AuditIntelligence;
  websiteText: string;
}

const STYLE_RULES = `STYLE & QUALITY RULES (follow strictly):
- You are a senior growth strategist at a high-end client-acquisition consultancy, not an AI copywriter. The deliverable must read like a paid audit a firm would charge $3,000–$15,000 for.
- Frame everything as conversion infrastructure / acquisition systems / revenue recovery — never as "copywriting."
- Be specific to THIS business type and THIS city. A Toronto med spa must not read like a Dallas roofer.
- Use the real data provided. NEVER fabricate reviews, stats, results, or "data" insights. Where review/competitor data is absent, you may make a clearly strategic assumption — but never present an assumption as if it came from data.
- Testimonials may be fictional but must be believable and locally grounded (real-sounding local names, neighborhoods, specific outcomes). No celebrity or generic names.
- Tie recommendations to practical business impact (more booked appointments, better lead quality, higher trust, less wasted time, higher close rates). No exaggerated claims.
- BANNED phrases/words: "unlock your potential", "supercharge", "revolutionary", "game-changing", "10x", "next-level", and obvious AI/guru filler.
- Tone: clear, tactical, premium, direct, human. No hype, no corporate filler.
- Return ONLY valid JSON matching the requested shape exactly. No commentary outside the JSON.`;

function profileBlock(b: BusinessProfile, websiteText: string): string {
  const lines = [
    `Name: ${b.name}`,
    `Industry: ${b.industry ?? "local business"}`,
    `Category: ${b.category ?? b.industry ?? "local business"}`,
    `City: ${b.city ?? "their local area"}`,
    `Rating: ${b.rating ? `${b.rating}/5 from ${b.reviewCount ?? 0} reviews` : "not available"}`,
    `Website: ${b.website ?? "none on record"}`,
    `Description: ${b.description ?? "none provided"}`,
  ];
  let block = `BUSINESS PROFILE\n${lines.join("\n")}`;
  if (websiteText) {
    block += `\n\nLIVE WEBSITE COPY (reference their ACTUAL services, offers, tone; use to spot weak CTAs / missing trust signals / outdated positioning):\n"""\n${websiteText}\n"""`;
  } else {
    block += `\n\nNo readable website copy was available — infer likely services from the niche and improve the weak positioning typical of this business type.`;
  }
  return block;
}

function contextHeader(ctx: GenerationContext): string {
  return [
    profileBlock(ctx.business, ctx.websiteText),
    "",
    "AUDIT INTELLIGENCE BRIEFING (heuristically extracted — treat as ground truth where marked real, and respect the labelled assumptions):",
    intelligenceToPromptBlock(ctx.intel),
  ].join("\n");
}

async function generateJson<T>(prompt: string): Promise<T> {
  const response = await openai.chat.completions.create({
    model: ASSET_MODEL,
    messages: [{ role: "user", content: prompt }],
    response_format: { type: "json_object" },
    temperature: 0.7,
  });
  const content = response.choices[0].message.content;
  if (!content) throw new Error("No content from AI");
  return JSON.parse(content) as T;
}

// ── FILE 1: Growth Audit + Landing Page ──────────────────────────────────────

async function generateFile1(ctx: GenerationContext): Promise<GrowthAuditFile> {
  const prompt = `${STYLE_RULES}

${contextHeader(ctx)}

TASK: Produce FILE 1 of the acquisition pack — a premium business growth audit AND a complete landing-page conversion blueprint for this ONE business. This is the flagship document; it must feel like a real consulting audit that diagnoses exactly where the business is losing leads, bookings, and revenue, then hands over the fix.

The audit must consider: weak positioning, unclear offer, weak CTAs, confusing customer journey, poor lead capture, missing qualification, weak booking flow, weak follow-up, lack of nurture, weak trust signals, poor use of reviews, outdated branding, weak mobile UX, weak local relevance, missed seasonal opportunities, lack of urgency, poor objection handling, poor perceived authority. Ground findings in the website signals + review + competitor intelligence above where present.

Local market intelligence must be specific to the city and niche (customer psychology, buying behavior, trust expectations, competitive saturation, seasonal demand, price sensitivity, local credibility markers).

The landing page copy must be clear, conversion-focused, locally relevant, niche-specific, believable, emotionally direct — not hypey, not generic.

Return JSON in EXACTLY this shape:
{
  "executiveSummary": "3-5 sentence sharp summary of the core opportunity and what this pack fixes",
  "growthAudit": {
    "overview": "2-4 sentence read on the current state of their acquisition system",
    "findings": [{"area": "e.g. Positioning", "finding": "specific finding", "severity": "high|medium|low"}]
  },
  "revenueLeaks": [
    {"issue": "...", "whyItMatters": "...", "impact": 9, "urgency": 8, "difficulty": 3, "recommendedFix": "...", "expectedImpact": "..."}
  ],
  "conversionBottlenecks": [{"stage": "e.g. Homepage → Inquiry", "problem": "...", "fix": "..."}],
  "localMarketIntelligence": {
    "customerPsychology": "...", "buyingBehavior": "...", "trustExpectations": "...",
    "competitiveSaturation": "...", "seasonalDemand": "...", "priceSensitivity": "...", "credibilityMarkers": "..."
  },
  "competitorPositioning": {
    "commonWeakMessaging": ["..."], "overusedClaims": ["..."], "trustGapsIgnored": ["..."],
    "opportunitiesToStandOut": ["..."], "recommendedAngle": "the positioning angle that makes this business the obvious, premium choice"
  },
  "trustGapAnalysis": [{"gap": "...", "impact": "...", "fix": "..."}],
  "fastestWins": ["3-6 highest-leverage quick wins"],
  "positioningStrategy": "recommended positioning strategy paragraph",
  "landingPage": {
    "heroHeadline": "...", "heroSubheadline": "...", "ctaBlock": "primary CTA block copy",
    "problemSection": "...", "solutionSection": "...", "offerSection": "...",
    "threeStepProcess": [{"step": "Step 1: ...", "description": "..."}],
    "benefits": ["..."], "trustSection": "how trust/proof is presented on the page",
    "testimonials": [{"name": "believable local name", "location": "neighborhood/area", "quote": "specific, believable outcome"}],
    "faq": [{"question": "real objection as a question", "answer": "..."}],
    "urgencyBlock": "honest urgency/scarcity copy (no fake countdowns)", "finalCta": "..."
  },
  "landingStructure": ["ordered section-by-section structure of the page"],
  "ctaStrategy": "CTA strategy explanation",
  "socialProofRecommendations": ["..."],
  "urgencyStrategy": "honest urgency/scarcity strategy",
  "implementationNotes": "how to deploy this page",
  "techStack": [{"tool": "e.g. Framer", "purpose": "..."}],
  "trackingAnalytics": ["specific tracking/analytics recommendations"],
  "loomTalkingPoints": ["talking points for a Loom walkthrough of the audit"],
  "beforeAfterAngles": [{"before": "current weak state", "after": "improved state"}],
  "salesEnablement": {
    "coldOutreachAngle": "...", "personalizedOpener": "...",
    "loomScriptBullets": ["..."], "proposalPositioning": "...",
    "discoveryCallPoints": ["..."], "objectionHandling": [{"objection": "...", "response": "..."}]
  }
}

Provide EXACTLY 5 items in revenueLeaks. Provide 4-7 findings, 3-5 conversionBottlenecks, 2-4 testimonials, 4-6 FAQ items.`;
  return generateJson<GrowthAuditFile>(prompt);
}

// ── FILE 2: Lead Qualification System ────────────────────────────────────────

async function generateFile2(ctx: GenerationContext): Promise<LeadQualificationFile> {
  const prompt = `${STYLE_RULES}

${contextHeader(ctx)}

TASK: Produce FILE 2 — a professional lead intake, scoring, and routing system for this business. It must reduce wasted calls and improve close rates, and be simple enough for a business owner or VA to implement.

The 7 questions must progressively qualify: identity, contact info, service need, urgency, seriousness, budget awareness, timeline/readiness. Each question needs a clear purpose and how it affects the lead score.

Lead tiers:
- Hot: high intent, urgent need, clear fit, ready timeline → contact within 1 hour
- Warm: interested but needs education, some friction, not urgent yet → follow up within 24 hours
- Cold/Nurture: low intent, unclear fit, weak urgency, bad fit, not ready → add to nurture sequence

Recommend a realistic automation stack only where relevant (e.g. Typeform/Jotform/HighLevel, Zapier/Make, Google Sheets/CRM, Calendly, SMS/email platform).

Return JSON in EXACTLY this shape:
{
  "formHeadline": "...",
  "formSubheadline": "...",
  "questions": [
    {"question": "...", "inputType": "text|email|phone|multiple choice|dropdown|yes-no", "options": ["only if applicable, else empty array"], "purpose": "...", "scoringImpact": "how answers move the score"}
  ],
  "leadScoring": {"rubric": "the simple scoring rubric", "hot": "hot criteria", "warm": "warm criteria", "cold": "cold/nurture criteria"},
  "routingLogic": [{"tier": "Hot", "action": "...", "timing": "within 1 hour"}],
  "automationWorkflow": ["ordered automation steps"],
  "thankYouPage": "thank-you page copy with the next step",
  "crmFields": ["recommended CRM fields to capture"],
  "followUpTiming": "follow-up timing guidance across tiers",
  "implementation": ["step-by-step implementation instructions"]
}

Provide EXACTLY 7 questions and EXACTLY 3 routingLogic entries (Hot, Warm, Cold).`;
  return generateJson<LeadQualificationFile>(prompt);
}

// ── FILE 3: 7-Day Email Nurture Sequence ─────────────────────────────────────

async function generateFile3(ctx: GenerationContext): Promise<EmailNurtureFile> {
  const prompt = `${STYLE_RULES}

${contextHeader(ctx)}

TASK: Produce FILE 3 — a 7-day email nurture sequence written as if the business owner personally wrote it. Human, personal, authoritative, simple, non-corporate, believable, specific to this business type and city. Not a newsletter, not robotic, not overhyped.

Sequence purpose by day:
1: Immediate welcome + credibility
2: Origin story / why we do this
3: Local proof / client story
4: Objection handling
5: Education + authority
6: Urgency + offer
7: Final direct ask

Return JSON in EXACTLY this shape:
{
  "emails": [
    {"day": 1, "timing": "immediately after opt-in", "subject": "...", "subjectB": "A/B alternative subject", "previewText": "inbox preview text", "body": "full email body with natural line breaks", "cta": "the call to action", "purpose": "welcome + credibility"}
  ]
}

Provide EXACTLY 7 emails, days 1 through 7, in order. Bodies should be complete and realistic (roughly 90-180 words each), signed off in the owner's voice.`;
  return generateJson<EmailNurtureFile>(prompt);
}

// ── FILE 4: SMS Follow-Up Sequence ───────────────────────────────────────────

async function generateFile4(ctx: GenerationContext): Promise<SmsFollowUpFile> {
  const prompt = `${STYLE_RULES}

${contextHeader(ctx)}

TASK: Produce FILE 4 — a copy-paste-ready SMS follow-up sequence of EXACTLY 6 messages. Human tone, no corporate language, no robotic phrasing, no fake urgency, a clear next step, designed to start replies. Keep under 160 characters where possible.

Timing:
1: within 2 minutes
2: 1 hour later if no reply
3: Day 2 morning
4: Day 3 social proof
5: Day 5 re-engagement
6: Day 7 final follow-up

Return JSON in EXACTLY this shape:
{
  "messages": [
    {"order": 1, "timing": "within 2 minutes", "message": "the SMS text", "charCount": 0, "psychology": "why this works", "replyStrategy": "how to handle the reply"}
  ]
}

Set charCount to the actual character count of the message string. Provide EXACTLY 6 messages in order.`;
  const file = await generateJson<SmsFollowUpFile>(prompt);
  // Trust our own count over the model's.
  file.messages = (file.messages ?? []).map((m) => ({
    ...m,
    charCount: (m.message ?? "").length,
  }));
  return file;
}

// ── FILE 5: Booking / Appointment System ─────────────────────────────────────

async function generateFile5(ctx: GenerationContext): Promise<BookingSystemFile> {
  const prompt = `${STYLE_RULES}

${contextHeader(ctx)}

TASK: Produce FILE 5 — a booking page + appointment show-up optimization system that reduces no-shows and increases appointment quality. Remove uncertainty by explaining what happens during the appointment, how long it takes, what to prepare, the outcome they can expect, why showing up matters, and how to reschedule. Tone: calm, confident, human, low-pressure, professional. No-show recovery must feel curious, human, helpful, open-door — never passive-aggressive.

Return JSON in EXACTLY this shape:
{
  "headline": "...",
  "subheadline": "...",
  "whatToExpect": ["..."],
  "threeStepBreakdown": [{"step": "Step 1: ...", "description": "..."}],
  "appointmentPositioning": "how the consultation/appointment is positioned as valuable and low-risk",
  "microSocialProof": ["short, believable social proof lines"],
  "confirmationEmail": {"subject": "...", "body": "..."},
  "reminderEmail24h": {"subject": "...", "body": "..."},
  "dayOfReminderSms": "the day-of reminder SMS text",
  "noShowRecoveryEmail": {"subject": "...", "body": "..."},
  "noShowRecoverySms1": "first no-show recovery SMS",
  "noShowRecoverySms2": "second no-show recovery SMS",
  "rescheduleFraming": "how rescheduling is framed",
  "showUpQualityNotes": "notes on improving show-up rate and appointment quality",
  "implementation": ["step-by-step implementation instructions"]
}

Provide 3 steps in threeStepBreakdown and 4-6 whatToExpect bullets.`;
  return generateJson<BookingSystemFile>(prompt);
}

// ── Orchestration ────────────────────────────────────────────────────────────

const SECTION_LABELS: Record<AssetSection, string> = {
  file1: "Growth Audit & Landing Page",
  file2: "Lead Qualification System",
  file3: "Email Nurture System",
  file4: "SMS Follow-Up System",
  file5: "Booking & Appointment System",
};

export function sectionLabel(section: AssetSection): string {
  return SECTION_LABELS[section];
}

export async function generateOneSection(
  section: AssetSection,
  ctx: GenerationContext
): Promise<AssetPack[AssetSection]> {
  switch (section) {
    case "file1":
      return generateFile1(ctx);
    case "file2":
      return generateFile2(ctx);
    case "file3":
      return generateFile3(ctx);
    case "file4":
      return generateFile4(ctx);
    case "file5":
      return generateFile5(ctx);
  }
}

export function buildMeta(ctx: GenerationContext) {
  return {
    businessName: ctx.business.name,
    city: ctx.business.city ?? "",
    industry: ctx.business.industry ?? ctx.business.category ?? "local business",
    generatedAt: new Date().toISOString(),
    dataConfidence: ctx.intel.dataConfidence,
    assumptions: ctx.intel.assumptions,
  };
}

export async function generateAssetPack(ctx: GenerationContext): Promise<AssetPack> {
  const [file1, file2, file3, file4, file5] = await Promise.all([
    generateFile1(ctx),
    generateFile2(ctx),
    generateFile3(ctx),
    generateFile4(ctx),
    generateFile5(ctx),
  ]);

  return { meta: buildMeta(ctx), file1, file2, file3, file4, file5 };
}
